[package]
edition = "2021"
license = "GPL-3.0-or-later"
name = "png-libimagequant"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imagequant = "4.2.0"
png = "0.17.6"
rgb = "0.8.33"
