[package]
name = "png-libimagequant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imagequant = "4.2.0"
png = "0.17.6"
rgb = "0.8.33"